volumes:
  pg_foodgram:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_foodgram:/var/lib/postgresql/data
  backend:
    image: andreiz82/foodgram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/backend/media
    depends_on:
      - db
  frontend:
    image: andreiz82/foodgram_frontend
    command: cp -r /app/build/. /frontend_static/
    env_file: .env
    volumes:
      - static:/frontend_static
  gateway:
    image: andreiz82/foodgram_gateway
    env_file: .env
    ports:
      - "9090:80"
    volumes:
      - static:/staticfiles
      - media:/media
    depends_on:
      - backend
