# Generated by Django 3.2.3 on 2025-08-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_alter_recipe_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlink',
            name='clicks',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
