# Generated by Django 3.2.3 on 2025-08-04 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_shortlink_clicks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortlink',
            name='clicks',
        ),
    ]
