name: Main Foodgram workflow

on:
  push:
    branches:
      - main

jobs:
  frontend_tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up nodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'

    - name: Install dependencies
      working-directory: ./frontend
      run: |
        npm install --legacy-peer-deps --no-audit --no-fund
        npm dedupe

    - name: Test frontend
      working-directory: ./frontend
      run: npm test -- --ci --watchAll=false
