name: Main Foodgram workflow

on:
  push:
    branches:
      - main

jobs:
  frontend_tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up nodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'yarn'
        cache-dependency-path: 'frontend/yarn.lock'

    - name: Clean install dependencies
      working-directory: ./frontend
      run: |
        rm -rf node_modules
        yarn install
        yarn dedupe

    - name: Test frontend
      working-directory: ./frontend
      run: npm test -- --ci --watchAll=false
