name: Main Foodgram workflow

on:
  push:
    branches:
      - main

jobs:
  frontend_tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up nodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
        cache-dependency-path: 'frontend/package-lock.json'

    - name: Clean install dependencies
      working-directory: ./frontend
      run: |
        rm -rf node_modules package-lock.json yarn.lock
        npm install -g npm@latest
        npm install
        npm ci --prefer-offline

    - name: Test frontend
      working-directory: ./frontend
      run: |
        cd frontend/
        run: npm test -- --ci --watchAll=false
