name: Main Foodgram workflow

on:
  push:
    branches:
      - main

jobs:
  frontend_tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up nodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: |
        cd frontend/
        npm ci --legacy-peer-deps

    - name: Test frontend
      run: |
        cd frontend/
        npm run test
