name: Main Foodgram workflow

on:
  push:
    branches:
      - main

jobs:
  frontend_tests:
  runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
        cache-dependency-path: 'frontend/package-lock.json'

    - name: Install dependencies
      working-directory: ./frontend
      run: |
        # Полная очистка перед установкой
        rm -rf node_modules
        # Установка зависимостей
        npm install --legacy-peer-deps --no-audit --no-fund --prefer-offline --loglevel=error
        npm dedupe

    - name: Run tests
      working-directory: ./frontend
      run: npm test -- --ci --watchAll=false
